#pragma once
#include <cstdint>

// geeg offsets
// Auto-generated by updater.ps1
// Primary source (theos): https://offsets.imtheo.lol/offsets.hpp
// Secondary source (Jonah): https://dumper.jonah.cool/version-f5a60436d48947d3/offsets.h

namespace Offsets {
    constexpr uintptr_t AirDensity = 0x0;
    constexpr uintptr_t GlobalWind = 0x0;
}

namespace AnimationTrack {
    constexpr uintptr_t Animation = 0xb8;
    constexpr uintptr_t Animator = 0x110;
    constexpr uintptr_t IsPlaying = 0xa58;
    constexpr uintptr_t Looped = 0xe5;
    constexpr uintptr_t Speed = 0xd4;
    constexpr uintptr_t TimePosition = 0xd8;
}

namespace Animator {
    constexpr uintptr_t ActiveAnimations = 0xb50;
}

namespace Atmosphere {
    constexpr uintptr_t Color = 0xb8;
    constexpr uintptr_t Decay = 0xc4;
    constexpr uintptr_t Density = 0xd0;
    constexpr uintptr_t Glare = 0xd4;
    constexpr uintptr_t Haze = 0xd8;
    constexpr uintptr_t Offset = 0xdc;
}

namespace Attachment {
    constexpr uintptr_t Position = 0xc4;
}

namespace BasePart {
    constexpr uintptr_t CastShadow = 0x135;
    constexpr uintptr_t Color3 = 0x1a8;
    constexpr uintptr_t Locked = 0x136;
    constexpr uintptr_t Massless = 0x137;
    constexpr uintptr_t Primitive = 0x188;
    constexpr uintptr_t Reflectance = 0x10c;
    constexpr uintptr_t Shape = 0x1b9;
    constexpr uintptr_t Transparency = 0x130;
}

namespace Beam {
    constexpr uintptr_t Attachment0 = 0x160;
    constexpr uintptr_t Attachment1 = 0x170;
    constexpr uintptr_t Brightness = 0x180;
    constexpr uintptr_t CurveSize0 = 0x184;
    constexpr uintptr_t CurveSize1 = 0x188;
    constexpr uintptr_t LightEmission = 0x18c;
    constexpr uintptr_t LightInfluence = 0x190;
    constexpr uintptr_t Texture = 0x140;
    constexpr uintptr_t TextureLength = 0x19c;
    constexpr uintptr_t TextureSpeed = 0x1a4;
    constexpr uintptr_t Width0 = 0x1a8;
    constexpr uintptr_t Width1 = 0x1ac;
    constexpr uintptr_t ZOffset = 0x1b0;
}

namespace BloomEffect {
    constexpr uintptr_t Enabled = 0xb0;
    constexpr uintptr_t Intensity = 0xb8;
    constexpr uintptr_t Size = 0xbc;
    constexpr uintptr_t Threshold = 0xc0;
}

namespace BlurEffect {
    constexpr uintptr_t Enabled = 0xb0;
    constexpr uintptr_t Size = 0xb8;
}

namespace ByteCode {
    constexpr uintptr_t Pointer = 0x10;
    constexpr uintptr_t Size = 0x20;
}

namespace Camera {
    constexpr uintptr_t CameraSubject = 0xc8;
    constexpr uintptr_t CameraType = 0x138;
    constexpr uintptr_t FieldOfView = 0x140;
    constexpr uintptr_t ImagePlaneDepth = 0x2d4;
    constexpr uintptr_t Position = 0xfc;
    constexpr uintptr_t Rotation = 0xd8;
    constexpr uintptr_t Viewport = 0x28c;
    constexpr uintptr_t ViewportSize = 0x2cc;
    constexpr uintptr_t CFrame = 0xD8;
    constexpr uintptr_t ViewportInt16 = 0x28C;
}

namespace CharacterMesh {
    constexpr uintptr_t BaseTextureId = 0xc8;
    constexpr uintptr_t BodyPart = 0x148;
    constexpr uintptr_t MeshId = 0xf8;
    constexpr uintptr_t OverlayTextureId = 0x128;
}

namespace ClickDetector {
    constexpr uintptr_t MaxActivationDistance = 0xe8;
    constexpr uintptr_t MouseIcon = 0xc8;
}

namespace Clothing {
    constexpr uintptr_t Color3 = 0x120;
    constexpr uintptr_t Template = 0x100;
}

namespace ColorCorrectionEffect {
    constexpr uintptr_t Brightness = 0xc4;
    constexpr uintptr_t Contrast = 0xc8;
    constexpr uintptr_t Enabled = 0xb0;
    constexpr uintptr_t TintColor = 0xb8;
}

namespace ColorGradingEffect {
    constexpr uintptr_t Enabled = 0xb0;
    constexpr uintptr_t TonemapperPreset = 0xb8;
}

namespace DataModel {
    constexpr uintptr_t CreatorId = 0x180;
    constexpr uintptr_t GameId = 0x188;
    constexpr uintptr_t GameLoaded = 0x5d0;
    constexpr uintptr_t JobId = 0x118;
    constexpr uintptr_t PlaceId = 0x190;
    constexpr uintptr_t PlaceVersion = 0x1ac;
    constexpr uintptr_t PrimitiveCount = 0x418;
    constexpr uintptr_t ScriptContext = 0x440;
    constexpr uintptr_t ServerIP = 0x5b8;
    constexpr uintptr_t ToRenderView1 = 0x1c8;
    constexpr uintptr_t ToRenderView2 = 0x8;
    constexpr uintptr_t ToRenderView3 = 0x28;
    constexpr uintptr_t Workspace = 0x158;
}

namespace DepthOfFieldEffect {
    constexpr uintptr_t Enabled = 0xb0;
    constexpr uintptr_t FarIntensity = 0xb8;
    constexpr uintptr_t FocusDistance = 0xbc;
    constexpr uintptr_t InFocusRadius = 0xc0;
    constexpr uintptr_t NearIntensity = 0xc4;
}

namespace DragDetector {
    constexpr uintptr_t ActivatedCursorIcon = 0x1c0;
    constexpr uintptr_t CursorIcon = 0xc8;
    constexpr uintptr_t MaxActivationDistance = 0xe8;
    constexpr uintptr_t MaxDragAngle = 0x2a8;
    constexpr uintptr_t MaxDragTranslation = 0x26c;
    constexpr uintptr_t MaxForce = 0x2ac;
    constexpr uintptr_t MaxTorque = 0x2b0;
    constexpr uintptr_t MinDragAngle = 0x2b4;
    constexpr uintptr_t MinDragTranslation = 0x278;
    constexpr uintptr_t ReferenceInstance = 0x1f0;
    constexpr uintptr_t Responsiveness = 0x2c0;
}

namespace FakeDataModel {
    constexpr uintptr_t Pointer = 0x8ca9cc8;
    constexpr uintptr_t RealDataModel = 0x1f8;
}

namespace GuiBase2D {
    constexpr uintptr_t AbsolutePosition = 0x10c;
    constexpr uintptr_t AbsoluteRotation = 0xe8;
    constexpr uintptr_t AbsoluteSize = 0x114;
}

namespace GuiObject {
    constexpr uintptr_t BackgroundColor3 = 0x540;
    constexpr uintptr_t BackgroundTransparency = 0x54c;
    constexpr uintptr_t BorderColor3 = 0x54c;
    constexpr uintptr_t Image = 0x988;
    constexpr uintptr_t LayoutOrder = 0x580;
    constexpr uintptr_t Position = 0x510;
    constexpr uintptr_t RichText = 0xb88;
    constexpr uintptr_t Rotation = 0xe8;
    constexpr uintptr_t ScreenGui_Enabled = 0x4c4;
    constexpr uintptr_t Size = 0x530;
    constexpr uintptr_t Text = 0xdf0;
    constexpr uintptr_t TextColor3 = 0xea0;
    constexpr uintptr_t Visible = 0x5ad;
    constexpr uintptr_t ZIndex = 0x5a4;
    constexpr uintptr_t Active = 0x5A8;
    constexpr uintptr_t AnchorPoint = 0x558;
    constexpr uintptr_t AutomaticSize = 0x560;
    constexpr uintptr_t BorderMode = 0x568;
    constexpr uintptr_t BorderSizePixel = 0x56C;
    constexpr uintptr_t ClipsDescendants = 0x5A9;
    constexpr uintptr_t GuiState = 0x578;
    constexpr uintptr_t Interactable = 0x5AB;
    constexpr uintptr_t Selectable = 0x5AC;
    constexpr uintptr_t SelectionOrder = 0x59C;
    constexpr uintptr_t SizeConstraint = 0x5A0;
}

namespace Humanoid {
    constexpr uintptr_t AutoJumpEnabled = 0x1d4;
    constexpr uintptr_t AutoRotate = 0x1d5;
    constexpr uintptr_t AutomaticScalingEnabled = 0x1d6;
    constexpr uintptr_t BreakJointsOnDeath = 0x1d7;
    constexpr uintptr_t CameraOffset = 0x128;
    constexpr uintptr_t DisplayDistanceType = 0x180;
    constexpr uintptr_t DisplayName = 0xb8;
    constexpr uintptr_t EvaluateStateMachine = 0x1d8;
    constexpr uintptr_t FloorMaterial = 0x184;
    constexpr uintptr_t Health = 0x190;
    constexpr uintptr_t HealthDisplayDistance = 0x188;
    constexpr uintptr_t HealthDisplayType = 0x18c;
    constexpr uintptr_t HipHeight = 0x194;
    constexpr uintptr_t HumanoidRootPart = 0x478;
    constexpr uintptr_t HumanoidState = 0x8c0;
    constexpr uintptr_t HumanoidStateID = 0x20;
    constexpr uintptr_t IsWalking = 0x967;
    constexpr uintptr_t Jump = 0x1da;
    constexpr uintptr_t JumpHeight = 0x1a0;
    constexpr uintptr_t JumpPower = 0x1a4;
    constexpr uintptr_t MaxHealth = 0x1a8;
    constexpr uintptr_t MaxSlopeAngle = 0x1ac;
    constexpr uintptr_t MoveDirection = 0x140;
    constexpr uintptr_t MoveToPart = 0x118;
    constexpr uintptr_t MoveToPoint = 0x164;
    constexpr uintptr_t NameDisplayDistance = 0x1b0;
    constexpr uintptr_t NameOcclusion = 0x1b4;
    constexpr uintptr_t PlatformStand = 0x1dc;
    constexpr uintptr_t PlatformStatePointer = 0x0;
    constexpr uintptr_t RequiresNeck = 0x1dd;
    constexpr uintptr_t RigType = 0x1c0;
    constexpr uintptr_t SeatPart = 0x108;
    constexpr uintptr_t Sit = 0x1dd;
    constexpr uintptr_t TargetPoint = 0x14c;
    constexpr uintptr_t UseJumpPower = 0x1e0;
    constexpr uintptr_t WalkTimer = 0x408;
    constexpr uintptr_t Walkspeed = 0x1d0;
    constexpr uintptr_t WalkspeedCheck = 0x3bc;
    constexpr uintptr_t WalkToPoint = 0x164;
}

namespace Instance {
    constexpr uintptr_t ChildrenEnd = 0x8;
    constexpr uintptr_t ChildrenStart = 0x78;
    constexpr uintptr_t ClassBase = 0x1b0;
    constexpr uintptr_t ClassDescriptor = 0x18;
    constexpr uintptr_t ClassName = 0x8;
    constexpr uintptr_t Name = 0x8;
    constexpr uintptr_t NameContainer = 0x70;
    constexpr uintptr_t Parent = 0x68;
    constexpr uintptr_t This = 0x8;
}

namespace Lighting {
    constexpr uintptr_t Ambient = 0xd0;
    constexpr uintptr_t Brightness = 0x118;
    constexpr uintptr_t ClockTime = 0xc8;
    constexpr uintptr_t ColorShift_Bottom = 0xe8;
    constexpr uintptr_t ColorShift_Top = 0xdc;
    constexpr uintptr_t EnvironmentDiffuseScale = 0x11c;
    constexpr uintptr_t EnvironmentSpecularScale = 0x120;
    constexpr uintptr_t ExposureCompensation = 0x124;
    constexpr uintptr_t FogColor = 0xf4;
    constexpr uintptr_t FogEnd = 0x12c;
    constexpr uintptr_t FogStart = 0x130;
    constexpr uintptr_t GeographicLatitude = 0x134;
    constexpr uintptr_t GlobalShadows = 0x144;
    constexpr uintptr_t GradientBottom = 0x190;
    constexpr uintptr_t GradientTop = 0x150;
    constexpr uintptr_t LightColor = 0x15c;
    constexpr uintptr_t LightDirection = 0x168;
    constexpr uintptr_t MoonPosition = 0x184;
    constexpr uintptr_t OutdoorAmbient = 0x100;
    constexpr uintptr_t Sky = 0x1c8;
    constexpr uintptr_t Source = 0x174;
    constexpr uintptr_t SunPosition = 0x178;
    constexpr uintptr_t Atmosphere = 0x1D8;
    constexpr uintptr_t ShadowSoftness = 0x13C;
}

namespace LocalScript {
    constexpr uintptr_t ByteCode = 0x0;
    constexpr uintptr_t GUID = 0xd0;
    constexpr uintptr_t Hash = 0x1a0;
}

namespace MaterialColors {
    constexpr uintptr_t Asphalt = 0x30;
    constexpr uintptr_t Basalt = 0x27;
    constexpr uintptr_t Brick = 0xf;
    constexpr uintptr_t Cobblestone = 0x33;
    constexpr uintptr_t Concrete = 0xc;
    constexpr uintptr_t CrackedLava = 0x2d;
    constexpr uintptr_t Glacier = 0x1b;
    constexpr uintptr_t Grass = 0x6;
    constexpr uintptr_t Ground = 0x2a;
    constexpr uintptr_t Ice = 0x36;
    constexpr uintptr_t LeafyGrass = 0x39;
    constexpr uintptr_t Limestone = 0x3f;
    constexpr uintptr_t Mud = 0x24;
    constexpr uintptr_t Pavement = 0x42;
    constexpr uintptr_t Rock = 0x18;
    constexpr uintptr_t Salt = 0x3c;
    constexpr uintptr_t Sand = 0x12;
    constexpr uintptr_t Sandstone = 0x21;
    constexpr uintptr_t Slate = 0x9;
    constexpr uintptr_t Snow = 0x1e;
    constexpr uintptr_t WoodPlanks = 0x15;
}

namespace MeshContentProvider {
    constexpr uintptr_t AssetID = 0x10;
    constexpr uintptr_t Cache = 0xf0;
    constexpr uintptr_t LRUCache = 0x20;
    constexpr uintptr_t MeshData = 0x40;
    constexpr uintptr_t ToMeshData = 0x40;
    constexpr uintptr_t LruHolder = 0xD8;
}

namespace MeshData {
    constexpr uintptr_t FaceEnd = 0x38;
    constexpr uintptr_t FaceStart = 0x30;
    constexpr uintptr_t VertexEnd = 0x8;
    constexpr uintptr_t VertexStart = 0x0;
}

namespace MeshPart {
    constexpr uintptr_t MeshId = 0x310;
    constexpr uintptr_t Texture = 0x340;
    constexpr uintptr_t TextureId = 0x340;
}

namespace Misc {
    constexpr uintptr_t Adornee = 0xf0;
    constexpr uintptr_t AnimationId = 0xc0;
    constexpr uintptr_t StringLength = 0x10;
    constexpr uintptr_t Value = 0xb8;
}

namespace Model {
    constexpr uintptr_t PrimaryPart = 0x258;
    constexpr uintptr_t Scale = 0x144;
}

namespace ModuleScript {
    constexpr uintptr_t ByteCode = 0x0;
    constexpr uintptr_t GUID = 0xd0;
    constexpr uintptr_t Hash = 0x148;
    constexpr uintptr_t IsCoreScript = 0x0;
    constexpr uintptr_t IsRobloxScript = 0x168;
}

namespace MouseService {
    constexpr uintptr_t InputObject = 0xf0;
    constexpr uintptr_t InputObject2 = 0x100;
    constexpr uintptr_t MousePosition = 0xd4;
    constexpr uintptr_t SensitivityPointer = 0x0;
}

namespace ParticleEmitter {
    constexpr uintptr_t Acceleration = 0x1e0;
    constexpr uintptr_t Brightness = 0x21c;
    constexpr uintptr_t Drag = 0x220;
    constexpr uintptr_t Lifetime = 0x1f4;
    constexpr uintptr_t LightEmission = 0x238;
    constexpr uintptr_t LightInfluence = 0x23c;
    constexpr uintptr_t Rate = 0x248;
    constexpr uintptr_t RotSpeed = 0x1fc;
    constexpr uintptr_t Rotation = 0x204;
    constexpr uintptr_t Speed = 0x20c;
    constexpr uintptr_t SpreadAngle = 0x214;
    constexpr uintptr_t Texture = 0x1c0;
    constexpr uintptr_t TimeScale = 0x25c;
    constexpr uintptr_t VelocityInheritance = 0x260;
    constexpr uintptr_t ZOffset = 0x264;
}

namespace Player {
    constexpr uintptr_t AccountAge = 0x35c;
    constexpr uintptr_t CameraMode = 0x370;
    constexpr uintptr_t DisplayName = 0x138;
    constexpr uintptr_t HealthDisplayDistance = 0x394;
    constexpr uintptr_t LocalPlayer = 0x130;
    constexpr uintptr_t LocaleId = 0x118;
    constexpr uintptr_t MaxZoomDistance = 0x368;
    constexpr uintptr_t MinZoomDistance = 0x36c;
    constexpr uintptr_t ModelInstance = 0x298;
    constexpr uintptr_t Mouse = 0x1208;
    constexpr uintptr_t NameDisplayDistance = 0x3a4;
    constexpr uintptr_t Team = 0x2d8;
    constexpr uintptr_t TeamColor = 0x3b0;
    constexpr uintptr_t UserId = 0xd0;
    constexpr uintptr_t Character = 0x298;
}

namespace PlayerConfigurer {
    constexpr uintptr_t Pointer = 0x0;
}

namespace PlayerMouse {
    constexpr uintptr_t Icon = 0xc8;
    constexpr uintptr_t Workspace = 0x150;
}

namespace Primitive {
    constexpr uintptr_t AssemblyAngularVelocity = 0x104;
    constexpr uintptr_t AssemblyLinearVelocity = 0xf8;
    constexpr uintptr_t Flags = 0x1b6;
    constexpr uintptr_t Material = 0x0;
    constexpr uintptr_t Owner = 0x210;
    constexpr uintptr_t Position = 0xec;
    constexpr uintptr_t Rotation = 0xc8;
    constexpr uintptr_t Size = 0x1bc;
    constexpr uintptr_t Validate = 0x6;
    constexpr uintptr_t CFrame = 0xC8;
    constexpr uintptr_t Orientation = 0xC8;
    constexpr uintptr_t Part = 0x210;
    constexpr uintptr_t PrimitiveFlags = 0x1B6;
}

namespace PrimitiveFlags {
    constexpr uintptr_t Anchored = 0x2;
    constexpr uintptr_t CanCollide = 0x8;
    constexpr uintptr_t CanQuery = 0x20;
    constexpr uintptr_t CanTouch = 0x10;
}

namespace ProximityPrompt {
    constexpr uintptr_t ActionText = 0xb0;
    constexpr uintptr_t Enabled = 0x136;
    constexpr uintptr_t GamepadKeyCode = 0x11c;
    constexpr uintptr_t HoldDuration = 0x120;
    constexpr uintptr_t KeyCode = 0x124;
    constexpr uintptr_t MaxActivationDistance = 0x128;
    constexpr uintptr_t ObjectText = 0xd0;
    constexpr uintptr_t RequiresLineOfSight = 0x137;
    constexpr uintptr_t KeyboardKeyCode = 0x124;
}

namespace RenderJob {
    constexpr uintptr_t FakeDataModel = 0x38;
    constexpr uintptr_t RealDataModel = 0x1f0;
    constexpr uintptr_t RenderView = 0x1d8;
}

namespace RenderView {
    constexpr uintptr_t DeviceD3D11 = 0x8;
    constexpr uintptr_t LightingValid = 0x150;
    constexpr uintptr_t SkyValid = 0x28d;
    constexpr uintptr_t VisualEngine = 0x10;
    constexpr uintptr_t SkyboxValid = 0x28D;
}

namespace RunService {
    constexpr uintptr_t HeartbeatFPS = 0xf4;
    constexpr uintptr_t HeartbeatTask = 0x3b8;
}

namespace Script {
    constexpr uintptr_t ByteCode = 0x0;
    constexpr uintptr_t GUID = 0xd0;
    constexpr uintptr_t Hash = 0x1a0;
}

namespace ScriptContext {
    constexpr uintptr_t RequireBypass = 0x0;
}

namespace Seat {
    constexpr uintptr_t Occupant = 0x210;
}

namespace Sky {
    constexpr uintptr_t MoonAngularSize = 0x244;
    constexpr uintptr_t MoonTextureId = 0xc8;
    constexpr uintptr_t SkyboxBk = 0xf8;
    constexpr uintptr_t SkyboxDn = 0x128;
    constexpr uintptr_t SkyboxFt = 0x158;
    constexpr uintptr_t SkyboxLf = 0x188;
    constexpr uintptr_t SkyboxOrientation = 0x238;
    constexpr uintptr_t SkyboxRt = 0x1b8;
    constexpr uintptr_t SkyboxUp = 0x1e8;
    constexpr uintptr_t StarCount = 0x248;
    constexpr uintptr_t SunAngularSize = 0x23c;
    constexpr uintptr_t SunTextureId = 0x218;
}

namespace Sound {
    constexpr uintptr_t IsPlaying = 0x140;
    constexpr uintptr_t Looped = 0x13d;
    constexpr uintptr_t PlaybackSpeed = 0x11c;
    constexpr uintptr_t RollOffMaxDistance = 0x120;
    constexpr uintptr_t RollOffMinDistance = 0x124;
    constexpr uintptr_t SoundGroup = 0xe8;
    constexpr uintptr_t SoundId = 0xc8;
    constexpr uintptr_t Volume = 0x130;
}

namespace SpawnLocation {
    constexpr uintptr_t AllowTeamChangeOnTouch = 0x1e8;
    constexpr uintptr_t Enabled = 0x1e9;
    constexpr uintptr_t ForcefieldDuration = 0x1e0;
    constexpr uintptr_t Neutral = 0x1ea;
    constexpr uintptr_t TeamColor = 0x1e4;
}

namespace SpecialMesh {
    constexpr uintptr_t MeshId = 0xf8;
    constexpr uintptr_t Scale = 0xc4;
    constexpr uintptr_t Offset = 0xB8;
    constexpr uintptr_t TextureId = 0x128;
}

namespace StatsItem {
    constexpr uintptr_t Value = 0xc8;
}

namespace SunRaysEffect {
    constexpr uintptr_t Enabled = 0xb0;
    constexpr uintptr_t Intensity = 0xb8;
    constexpr uintptr_t Spread = 0xbc;
}

namespace SurfaceAppearance {
    constexpr uintptr_t AlphaMode = 0x1f0;
    constexpr uintptr_t Color = 0x1d8;
    constexpr uintptr_t ColorMap = 0xc8;
    constexpr uintptr_t EmissiveMaskContent = 0xf8;
    constexpr uintptr_t EmissiveStrength = 0x1f4;
    constexpr uintptr_t EmissiveTint = 0x1e4;
    constexpr uintptr_t MetalnessMap = 0x128;
    constexpr uintptr_t NormalMap = 0x158;
    constexpr uintptr_t RoughnessMap = 0x188;
}

namespace TaskScheduler {
    constexpr uintptr_t JobEnd = 0xd0;
    constexpr uintptr_t JobName = 0x18;
    constexpr uintptr_t JobStart = 0xc8;
    constexpr uintptr_t MaxFPS = 0xb0;
    constexpr uintptr_t Pointer = 0x8a44d68;
}

namespace Team {
    constexpr uintptr_t BrickColor = 0xb8;
    constexpr uintptr_t TeamColor = 0xB8;
}

namespace Terrain {
    constexpr uintptr_t GrassLength = 0x1e8;
    constexpr uintptr_t MaterialColors = 0x4b0;
    constexpr uintptr_t WaterColor = 0x1d8;
    constexpr uintptr_t WaterReflectance = 0x1f0;
    constexpr uintptr_t WaterTransparency = 0x1f4;
    constexpr uintptr_t WaterWaveSize = 0x1f8;
    constexpr uintptr_t WaterWaveSpeed = 0x1fc;
}

namespace Textures {
    constexpr uintptr_t Decal_Texture = 0x1b0;
    constexpr uintptr_t Texture_Texture = 0x1b0;
}

namespace Tool {
    constexpr uintptr_t CanBeDropped = 0x4b8;
    constexpr uintptr_t Enabled = 0x4b9;
    constexpr uintptr_t Grip = 0x4ac;
    constexpr uintptr_t ManualActivationOnly = 0x4ba;
    constexpr uintptr_t RequiresHandle = 0x4bb;
    constexpr uintptr_t TextureId = 0x360;
    constexpr uintptr_t Tooltip = 0x468;
    constexpr uintptr_t GripForward = 0x4A0;
    constexpr uintptr_t GripPos = 0x4AC;
    constexpr uintptr_t GripRight = 0x488;
    constexpr uintptr_t GripUp = 0x494;
}

namespace UnionOperation {
    constexpr uintptr_t AssetId = 0x310;
}

namespace UserInputService {
    constexpr uintptr_t WindowInputState = 0x2c0;
}

namespace VehicleSeat {
    constexpr uintptr_t MaxSpeed = 0x228;
    constexpr uintptr_t SteerFloat = 0x22c;
    constexpr uintptr_t ThrottleFloat = 0x230;
    constexpr uintptr_t Torque = 0x234;
    constexpr uintptr_t TurnSpeed = 0x238;
    constexpr uintptr_t Occupant = 0x208;
}

namespace VisualEngine {
    constexpr uintptr_t Dimensions = 0xae0;
    constexpr uintptr_t FakeDataModel = 0xac0;
    constexpr uintptr_t Pointer = 0x82e2128;
    constexpr uintptr_t RenderView = 0xc00;
    constexpr uintptr_t ViewMatrix = 0x180;
}

namespace Weld {
    constexpr uintptr_t Part0 = 0x118;
    constexpr uintptr_t Part1 = 0x128;
}

namespace WeldConstraint {
    constexpr uintptr_t Part0 = 0xb8;
    constexpr uintptr_t Part1 = 0xc8;
}

namespace WindowInputState {
    constexpr uintptr_t CapsLock = 0x40;
    constexpr uintptr_t CurrentTextBox = 0x48;
}

namespace Workspace {
    constexpr uintptr_t CurrentCamera = 0x498;
    constexpr uintptr_t DistributedGameTime = 0x4b8;
    constexpr uintptr_t ReadOnlyGravity = 0x9c8;
    constexpr uintptr_t World = 0x368;
}

namespace World {
    constexpr uintptr_t AirProperties = 0x0;
    constexpr uintptr_t FallenPartsDestroyHeight = 0x0;
    constexpr uintptr_t Gravity = 0x1b4;
    constexpr uintptr_t Primitives = 0x0;
    constexpr uintptr_t worldStepsPerSec = 0x0;
    constexpr uintptr_t WorldSteps = 0x720;
}

namespace CachedItem {
    constexpr uintptr_t FileMeshData = 0x40;
}

namespace ClassDescriptor {
    constexpr uintptr_t ClassName = 0x8;
    constexpr uintptr_t Creator = 0x230;
    constexpr uintptr_t EventDescriptors = 0x88;
    constexpr uintptr_t FunctionDescriptors = 0xD0;
    constexpr uintptr_t PropertyDescriptors = 0x40;
}

namespace Creator {
    constexpr uintptr_t MapEnd = 0x83403D8;
    constexpr uintptr_t MapStart = 0x83403D0;
}

namespace Descriptor {
    constexpr uintptr_t Name = 0x8;
}

namespace FileMeshData {
    constexpr uintptr_t AabbMax = 0x2BC;
    constexpr uintptr_t AabbMin = 0x2B0;
    constexpr uintptr_t Faces = 0x30;
    constexpr uintptr_t FacesEnd = 0x38;
    constexpr uintptr_t Vertices = 0x0;
    constexpr uintptr_t VerticesEnd = 0x8;
}

namespace Fire {
    constexpr uintptr_t FireProximityPrompt = 0x309BD00;
}

namespace FunctionDescriptor {
    constexpr uintptr_t Function = 0x80;
}

namespace Functions {
    constexpr uintptr_t Clone = 0x1619170;
    constexpr uintptr_t Destroy = 0x1619190;
    constexpr uintptr_t FindPartOnRay = 0xEB3460;
    constexpr uintptr_t FindPartOnRayWithIgnoreList = 0xEB34E0;
    constexpr uintptr_t FindPartOnRayWithWhitelist = 0xEB3570;
    constexpr uintptr_t FireServer = 0xC99010;
    constexpr uintptr_t Print = 0x1C68FE0;
    constexpr uintptr_t RaisePropertyChanged = 0x2F75780;
    constexpr uintptr_t Raycast = 0xEAAA10;
    constexpr uintptr_t SetParent = 0xEA4D6C;
    constexpr uintptr_t SetParentInternal = 0x1CB1AD0;
    constexpr uintptr_t Shapecast = 0xEAC3D0;
}

namespace Highlight {
    constexpr uintptr_t Adornee = 0xB8;
    constexpr uintptr_t DepthMode = 0xE0;
    constexpr uintptr_t Enabled = 0xF4;
    constexpr uintptr_t FillColor = 0xC8;
    constexpr uintptr_t FillTransparency = 0xE4;
    constexpr uintptr_t OutlineColor = 0xD4;
    constexpr uintptr_t OutlineTransparency = 0xEC;
}

namespace HopperBin {
    constexpr uintptr_t BinType = 0x468;
}

namespace ICreator {
    constexpr uintptr_t Create = 0x0;
}

namespace InputObject {
    constexpr uintptr_t MousePosition = 0xD4;
}

namespace LightingParameters {
    constexpr uintptr_t GeographicLatitude = 0x134;
    constexpr uintptr_t LightColor = 0x15C;
    constexpr uintptr_t LightDirection = 0x168;
    constexpr uintptr_t SkyAmbient = 0x150;
    constexpr uintptr_t SkyAmbient2 = 0x138;
    constexpr uintptr_t Source = 0x174;
    constexpr uintptr_t TrueMoonPosition = 0x184;
    constexpr uintptr_t TrueSunPosition = 0x178;
}

namespace LruHolder {
    constexpr uintptr_t MemEnforcedLRUCache = 0x20;
}

namespace LruNode {
    constexpr uintptr_t CachedItem = 0x40;
    constexpr uintptr_t MeshId = 0x10;
    constexpr uintptr_t Next = 0x0;
}

namespace MemEnforcedLRUCache {
    constexpr uintptr_t Head = 0x8;
}

namespace Players {
    constexpr uintptr_t LocalPlayer = 0x130;
}

namespace PropertyDescriptor {
    constexpr uintptr_t GetSetImpl = 0x90;
    constexpr uintptr_t TType = 0x68;
}

namespace TextButton {
    constexpr uintptr_t AutoButtonColor = 0x9C4;
    constexpr uintptr_t ContentText = 0xE08;
    constexpr uintptr_t LineHeight = 0xF20;
    constexpr uintptr_t LocalizedText = 0xE08;
    constexpr uintptr_t MaxVisibleGraphemes = 0x113C;
    constexpr uintptr_t Modal = 0x9C5;
    constexpr uintptr_t RichText = 0x101E;
    constexpr uintptr_t Selected = 0x9C6;
    constexpr uintptr_t Text = 0xE08;
    constexpr uintptr_t TextColor3 = 0x1120;
    constexpr uintptr_t TextDirection = 0xFC0;
    constexpr uintptr_t TextScaled = 0x1016;
    constexpr uintptr_t TextSize = 0x1144;
    constexpr uintptr_t TextStrokeColor3 = 0x112C;
    constexpr uintptr_t TextStrokeTransparency = 0x1148;
    constexpr uintptr_t TextTransparency = 0x114C;
    constexpr uintptr_t TextTruncate = 0x1150;
    constexpr uintptr_t TextWrapped = 0x1018;
    constexpr uintptr_t TextXAlignment = 0x1154;
    constexpr uintptr_t TextYAlignment = 0xF68;
}

namespace TextLabel {
    constexpr uintptr_t ContentText = 0xB88;
    constexpr uintptr_t LineHeight = 0xCA0;
    constexpr uintptr_t LocalizedText = 0xB88;
    constexpr uintptr_t MaxVisibleGraphemes = 0xEBC;
    constexpr uintptr_t RichText = 0xD9E;
    constexpr uintptr_t Text = 0xB88;
    constexpr uintptr_t TextColor3 = 0xEA0;
    constexpr uintptr_t TextDirection = 0xD40;
    constexpr uintptr_t TextScaled = 0xD96;
    constexpr uintptr_t TextSize = 0xEC4;
    constexpr uintptr_t TextStrokeColor3 = 0xEAC;
    constexpr uintptr_t TextStrokeTransparency = 0xEC8;
    constexpr uintptr_t TextTransparency = 0xECC;
    constexpr uintptr_t TextTruncate = 0xED0;
    constexpr uintptr_t TextWrapped = 0xD98;
    constexpr uintptr_t TextXAlignment = 0xED4;
    constexpr uintptr_t TextYAlignment = 0xCE8;
}

namespace Types {
    constexpr uintptr_t AllTypes = 0x8836AD8;
}

namespace Value {
    constexpr uintptr_t Value = 0xB8;
}

namespace enums {
    enum class ReflectionType : int {
        Null = 0x0,
        Bool = 0x1,
        Int = 0x2,
        Int64 = 0x3,
        Float = 0x4,
        Double = 0x5,
        String = 0x6,
        ProtectedString = 0x7,
        Instance = 0x8,
        Instances = 0x9,
        Ray = 0xA,
        Vector2 = 0xB,
        Vector3 = 0xC,
        Vector2int16 = 0xD,
        Vector3int16 = 0xE,
        Rect2D = 0xF,
        CoordinateFrame = 0x10,
        Color3 = 0x11,
        Color3uint8 = 0x12,
        UDim = 0x13,
        UDim2 = 0x14,
        Faces = 0x15,
        Axes = 0x16,
        Region3 = 0x17,
        Region3int16 = 0x18,
        CellId = 0x19,
        GuidData = 0x1A,
        PhysicalProperties = 0x1B,
        BrickColor = 0x1C,
        SystemAddress = 0x1D,
        BinaryString = 0x1E,
        Surface = 0x1F,
        CollectionHandle = 0x20,
        Enum = 0x21,
        Property = 0x22,
        Tuple = 0x23,
        Array = 0x24,
        Dictionary = 0x25,
        Map = 0x26,
        Variant = 0x27,
        GenericFunction = 0x28,
        Function = 0x29,
        ColorSequence = 0x2A,
        ColorSequenceKeypoint = 0x2B,
        NumberRange = 0x2C,
        NumberSequence = 0x2D,
        NumberSequenceKeypoint = 0x2E,
        Connection = 0x30,
        ContentId = 0x31,
        DescribedBase = 0x32,
        RefType = 0x33,
        EventInstance = 0x36,
        TweenInfo = 0x37,
        DockWidgetPluginGuiInfo = 0x38,
        PluginDrag = 0x39,
        Random = 0x3A,
        PathWaypoint = 0x3B,
        FloatCurveKey = 0x3C,
        RotationCurveKey = 0x3D,
        ValueCurveKey = 0x3E,
        SharedString = 0x3F,
        DateTime = 0x40,
        RaycastParams = 0x41,
        RaycastResult = 0x42,
        OverlapParams = 0x43,
        LazyTable = 0x44,
        DebugTable = 0x45,
        CatalogSearchParams = 0x46,
        OptionalCoordinateFrame = 0x47,
        CSGPropertyData = 0x48,
        UniqueId = 0x49,
        Font = 0x4A,
        SharedTable = 0x4B,
        SharedTableIterator = 0x4C,
        AnimationMask = 0x4D,
        AnimationPose = 0x4E,
        ClipEvaluator = 0x4F,
        OpenCloudModel = 0x50,
        InstanceRef = 0x51,
        SecurityCapabilities = 0x52,
        ArticulatedJoint = 0x53,
        AnimationContext = 0x54,
        Secret = 0x55,
        Buffer = 0x56,
        Integer = 0x57,
        Path2DControlPoint = 0x58,
        ReplicationPV = 0x59,
        FacsReplicationData = 0x5A,
        AnimationMaskModifier = 0x5B,
        Content = 0x5C,
        NetAssetHandle = 0x5D,
        NetAssetRef = 0x5E,
        Object = 0x5F,
        AdReward = 0x60,
        AssetContentMap = 0x61,
        SlimReplicationData = 0x62,
        User = 0x63,
        WebViewParams = 0x64,
        AnimTrackPlayState = 0x65,
        AnimTrackMetadata = 0x66,
        AnimTrackWeight = 0x67,
        ScopedInstanceIdentity = 0x68,
    };

}

